name: build
on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12" ]
        os: [ ubuntu-latest ]
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install --upgrade coveralls
          pip show twine
          pip freeze
          pip install twine --upgrade
          pip install packaging --upgrade
      - name: Run tests
        run: coverage run -m unittest discover -s tests -t tests

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: ${{ matrix.os }} - ${{ matrix.python-version }}
          COVERALLS_PARALLEL: true
